from __future__ import annotations

from .models import Capability, ConfirmationMode, KernelMode, Risk


def _cap(
    tool_name: str,
    command: str,
    description: str,
    operation: str,
    *,
    writes: bool = False,
    risk: Risk = Risk.LOW,
    confirmation: ConfirmationMode = ConfirmationMode.DIRECT,
    aliases: tuple[str, ...] = (),
    arguments: dict | None = None,
) -> Capability:
    return Capability(
        tool_name=tool_name,
        command=command,
        description=description,
        kernel=KernelMode.SYSTEM,
        executor="massive_build",
        operation=operation,
        risk=risk,
        confirmation=confirmation,
        writes=writes,
        aliases=aliases,
        arguments=arguments or {},
    )


MASSIVE_BUILD_CAPABILITIES: tuple[Capability, ...] = (
    _cap(
        "project.cell.create.v1", "project cell create",
        "Create a Build Cell for an independently investigable or implementable project domain.",
        "cell_create", writes=True, aliases=("build cell", "建立協同單元"),
        arguments={
            "project_id": {"type": "string", "required": True},
            "name": {"type": "string", "required": True},
            "goal": {"type": "string", "required": True},
            "domain": {"type": "string", "required": False},
            "strategy": {"type": "string", "required": False},
            "base_commit": {"type": "string", "required": False},
            "contract_ids": {"type": "array", "required": False},
            "dependencies": {"type": "array", "required": False},
            "metadata": {"type": "object", "required": False},
        },
    ),
    _cap(
        "project.cell.update.v1", "project cell update",
        "Update Build Cell progress, assigned Work Orders, worktree or status.",
        "cell_update", writes=True,
        arguments={
            "cell_id": {"type": "string", "required": True},
            "status": {"type": "string", "required": False},
            "progress": {"type": "number", "required": False},
            "worktree_id": {"type": "string", "required": False},
            "assigned_work_orders": {"type": "array", "required": False},
            "metadata": {"type": "object", "required": False},
        },
    ),
    _cap(
        "project.massive.inspect.v1", "project massive inspect",
        "Read Build Cells, contracts, leases, worktrees, batches, integrations and wiring evidence.",
        "project_inspect",
        arguments={"project_id": {"type": "string", "required": True}},
    ),
    _cap(
        "project.contract.create.v1", "project contract create",
        "Create a versioned draft, provisional or stable shared project contract.",
        "contract_create", writes=True, aliases=("API contract", "建立共享契約"),
        arguments={
            "project_id": {"type": "string", "required": True},
            "contract_type": {"type": "string", "required": True},
            "name": {"type": "string", "required": True},
            "schema": {"type": "object", "required": True},
            "status": {"type": "string", "required": False},
            "owner": {"type": "string", "required": False},
            "consumers": {"type": "array", "required": False},
            "evidence": {"type": "array", "required": False},
            "supersedes_id": {"type": "string", "required": False},
        },
    ),
    _cap(
        "project.contract.inspect.v1", "project contract inspect",
        "Read the current versioned contracts available to all Build Cells.",
        "contract_inspect",
        arguments={
            "project_id": {"type": "string", "required": True},
            "include_deprecated": {"type": "boolean", "required": False},
        },
    ),
    _cap(
        "project.write_lease.acquire.v1", "project write lease acquire",
        "Acquire an expiring write scope so parallel Agents do not edit overlapping code regions.",
        "lease_acquire", writes=True,
        arguments={
            "project_id": {"type": "string", "required": True},
            "scope_type": {"type": "string", "required": True},
            "scope": {"type": "string", "required": True},
            "cell_id": {"type": "string", "required": False},
            "owner_work_order_id": {"type": "string", "required": False},
            "base_commit": {"type": "string", "required": False},
            "lease_seconds": {"type": "integer", "required": False},
            "metadata": {"type": "object", "required": False},
        },
    ),
    _cap(
        "project.write_lease.release.v1", "project write lease release",
        "Release a Build Cell or Agent write scope.",
        "lease_release", writes=True,
        arguments={"lease_id": {"type": "string", "required": True}},
    ),
    _cap(
        "project.worktree.create.v1", "project worktree create",
        "Create an isolated Git worktree for a Build Cell using a chosen branch and base ref.",
        "worktree_create", writes=True, risk=Risk.HIGH, confirmation=ConfirmationMode.EXPLICIT,
        aliases=("git worktree", "建立隔離工作區"),
        arguments={
            "project_id": {"type": "string", "required": True},
            "cell_id": {"type": "string", "required": False},
            "cwd": {"type": "string", "required": False},
            "path": {"type": "string", "required": True},
            "branch": {"type": "string", "required": True},
            "base_ref": {"type": "string", "required": False},
        },
    ),
    _cap(
        "project.worktree.remove.v1", "project worktree remove",
        "Remove a registered isolated Git worktree after integration or cancellation.",
        "worktree_remove", writes=True, risk=Risk.HIGH, confirmation=ConfirmationMode.EXPLICIT,
        arguments={
            "worktree_id": {"type": "string", "required": True},
            "cwd": {"type": "string", "required": False},
            "force": {"type": "boolean", "required": False},
        },
    ),
    _cap(
        "project.batch.create.v1", "project batch create",
        "Create a reviewable code batch within a Build Cell.",
        "batch_create", writes=True,
        arguments={
            "project_id": {"type": "string", "required": True},
            "title": {"type": "string", "required": True},
            "goal": {"type": "string", "required": True},
            "cell_id": {"type": "string", "required": False},
            "base_commit": {"type": "string", "required": False},
            "metadata": {"type": "object", "required": False},
        },
    ),
    _cap(
        "project.batch.update.v1", "project batch update",
        "Persist a code batch diff summary, receipts, verification and acceptance state.",
        "batch_update", writes=True,
        arguments={
            "batch_id": {"type": "string", "required": True},
            "status": {"type": "string", "required": False},
            "head_commit": {"type": "string", "required": False},
            "changed_files": {"type": "array", "required": False},
            "added_lines": {"type": "integer", "required": False},
            "deleted_lines": {"type": "integer", "required": False},
            "diff_summary": {"type": "object", "required": False},
            "receipts": {"type": "array", "required": False},
            "verification": {"type": "object", "required": False},
            "metadata": {"type": "object", "required": False},
        },
    ),
    _cap(
        "project.integration.create.v1", "project integration create",
        "Create a domain or project integration record for selected Cells and code batches.",
        "integration_create", writes=True,
        arguments={
            "project_id": {"type": "string", "required": True},
            "title": {"type": "string", "required": True},
            "scope": {"type": "string", "required": False},
            "source_cells": {"type": "array", "required": False},
            "source_batches": {"type": "array", "required": False},
            "base_commit": {"type": "string", "required": False},
            "metadata": {"type": "object", "required": False},
        },
    ),
    _cap(
        "project.integration.update.v1", "project integration update",
        "Persist merge conflicts, integration receipts, verification and result commit.",
        "integration_update", writes=True,
        arguments={
            "integration_id": {"type": "string", "required": True},
            "status": {"type": "string", "required": False},
            "result_commit": {"type": "string", "required": False},
            "conflicts": {"type": "array", "required": False},
            "receipts": {"type": "array", "required": False},
            "verification": {"type": "object", "required": False},
            "metadata": {"type": "object", "required": False},
        },
    ),
    _cap(
        "project.wiring.verify.v1", "project wiring verify",
        "Persist evidence for UI-to-event-to-API-to-service-to-repository-to-database-to-Receipt wiring.",
        "wiring_upsert", writes=True,
        arguments={
            "project_id": {"type": "string", "required": True},
            "feature_key": {"type": "string", "required": True},
            "title": {"type": "string", "required": True},
            "states": {"type": "object", "required": True},
            "evidence": {"type": "array", "required": False},
            "work_order_id": {"type": "string", "required": False},
            "metadata": {"type": "object", "required": False},
        },
    ),
)
