from __future__ import annotations

from .models import Capability, ConfirmationMode, KernelMode, Risk


def _cap(
    tool_name: str,
    command: str,
    description: str,
    operation: str,
    *,
    writes: bool = False,
    aliases: tuple[str, ...] = (),
    arguments: dict | None = None,
) -> Capability:
    return Capability(
        tool_name=tool_name,
        command=command,
        description=description,
        kernel=KernelMode.SYSTEM,
        executor="mega_project",
        operation=operation,
        risk=Risk.LOW,
        confirmation=ConfirmationMode.DIRECT,
        writes=writes,
        aliases=aliases,
        arguments=arguments or {},
    )


MEGA_PROJECT_CAPABILITIES: tuple[Capability, ...] = (
    _cap(
        "tools.search.v1",
        "tools search",
        "Search the persistent Tool Knowledge Registry by natural-language intent.",
        "tools_search",
        aliases=("find tools", "搜索工具", "查詢工具庫"),
        arguments={
            "query": {"type": "string", "required": True},
            "categories": {"type": "array", "required": False},
            "limit": {"type": "integer", "required": False},
        },
    ),
    _cap(
        "tools.inspect.v1",
        "tools inspect",
        "Inspect one tool's schema, risk, requirements, examples and related tools.",
        "tools_inspect",
        aliases=("tool schema", "查看工具", "工具詳情"),
        arguments={"tool_name": {"type": "string", "required": True}},
    ),
    _cap(
        "tools.recommend.v1",
        "tools recommend",
        "Return advisory tool candidates for the current goal; recommendations never force a workflow.",
        "tools_recommend",
        aliases=("recommend tools", "推薦工具", "大型項目工具"),
        arguments={
            "query": {"type": "string", "required": True},
            "project_id": {"type": "string", "required": False},
            "limit": {"type": "integer", "required": False},
        },
    ),
    _cap(
        "project.create.v1",
        "project create",
        "Create a durable Mega Project knowledge space without imposing a fixed workflow.",
        "project_create",
        writes=True,
        aliases=("mega project", "大型項目", "超大任務"),
        arguments={
            "title": {"type": "string", "required": True},
            "goal": {"type": "string", "required": True},
            "conversation_id": {"type": "string", "required": False},
            "director_run_id": {"type": "string", "required": False},
            "phase": {"type": "string", "required": False},
            "metadata": {"type": "object", "required": False},
        },
    ),
    _cap(
        "project.inspect.v1",
        "project inspect",
        "Read a Mega Project's findings, decisions, steps and latest checkpoint.",
        "project_inspect",
        aliases=("project status", "項目狀態", "項目知識"),
        arguments={"project_id": {"type": "string", "required": True}},
    ),
    _cap(
        "project.checkpoint.v1",
        "project checkpoint",
        "Persist the main AI's current project understanding and phase without enforcing transitions.",
        "project_checkpoint",
        writes=True,
        aliases=("save project state", "保存項目檢查點"),
        arguments={
            "project_id": {"type": "string", "required": True},
            "summary": {"type": "string", "required": True},
            "phase": {"type": "string", "required": False},
            "payload": {"type": "object", "required": False},
        },
    ),
    _cap(
        "project.finding.store.v1",
        "project finding store",
        "Store a verified fact, inference, risk, constraint, unknown, recommendation or conflict with evidence.",
        "finding_store",
        writes=True,
        aliases=("store finding", "保存調查結果", "項目發現"),
        arguments={
            "project_id": {"type": "string", "required": True},
            "finding_type": {"type": "string", "required": True},
            "claim": {"type": "string", "required": True},
            "domain": {"type": "string", "required": False},
            "confidence": {"type": "number", "required": False},
            "evidence": {"type": "array", "required": False},
            "source_work_order_id": {"type": "string", "required": False},
            "supersedes_id": {"type": "string", "required": False},
            "metadata": {"type": "object", "required": False},
        },
    ),
    _cap(
        "project.finding.search.v1",
        "project finding search",
        "Search distilled project knowledge while retaining links to raw evidence.",
        "finding_search",
        aliases=("search findings", "搜索項目知識", "查找調查結論"),
        arguments={
            "project_id": {"type": "string", "required": True},
            "query": {"type": "string", "required": False},
            "finding_types": {"type": "array", "required": False},
            "limit": {"type": "integer", "required": False},
        },
    ),
    _cap(
        "project.step.create.v1",
        "project step create",
        "Create a freely ordered, dependency-aware project step chosen by the main AI.",
        "step_create",
        writes=True,
        aliases=("create step", "建立項目步驟"),
        arguments={
            "project_id": {"type": "string", "required": True},
            "title": {"type": "string", "required": True},
            "goal": {"type": "string", "required": True},
            "phase": {"type": "string", "required": False},
            "status": {"type": "string", "required": False},
            "sequence": {"type": "integer", "required": False},
            "parent_step_id": {"type": "string", "required": False},
            "dependencies": {"type": "array", "required": False},
            "metadata": {"type": "object", "required": False},
        },
    ),
    _cap(
        "project.step.update.v1",
        "project step update",
        "Update a project step with work assignment, Receipts, verification or status chosen by the main AI.",
        "step_update",
        writes=True,
        aliases=("update step", "更新項目步驟", "驗證步驟"),
        arguments={
            "step_id": {"type": "string", "required": True},
            "status": {"type": "string", "required": False},
            "assigned_work_order_id": {"type": "string", "required": False},
            "implementation_receipts": {"type": "array", "required": False},
            "verification": {"type": "object", "required": False},
            "metadata": {"type": "object", "required": False},
        },
    ),
)
